name: solar system
on:
    on:
        push:
          branches:
            - main
    
      
        pull_request:
          branches:
            - main

      
        workflow_dispatch:
          inputs:
            environment:
              description: 'Environment to deploy'
              required: true
              default: 'staging'
       


jobs:
  unit-test:
    name: Unit Test
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        node-version: [14.x, 16.x]
        exclude:
            - node-version: 18
            os: macos-latest
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2


    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install Dependencies
      run: npm install
    - name: Run Tests
      run: npm test


    